CREATE TABLE IF NOT EXISTS users (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL);
	
CREATE TABLE IF NOT EXISTS surveys (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	owner_id INT NOT NULL,
	title VARCHAR(255) NOT NULL,
	is_disabled BOOLEAN NOT NULL,
	FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE CASCADE);
	
CREATE TABLE IF NOT EXISTS questions (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	survey_id INT NOT NULL,
	question VARCHAR(255) NOT NULL,
	FOREIGN KEY(survey_id) REFERENCES surveys(id) ON DELETE CASCADE);
	
CREATE TABLE IF NOT EXISTS answers (
	question_id INT NOT NULL,
	survey_id INT NOT NULL,
	user_id INT NOT NULL,
	answer INT NOT NULL,
	FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE,
	FOREIGN KEY(survey_id) REFERENCES surveys(id) ON DELETE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);