export { default as Login } from "./Login/Login";
export { default as SignUp } from "./Login/SignUp";
export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as Menu } from "./Menu";
export { default as Contact } from "./Contact";
export { default as Posts } from "./Appointments/Posts";
export { default as Post } from "./Appointments/Post";